// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe1n8VOnrLcgP8GkN92nlVd95A3DUb9Z4',
    appId: '1:467627933593:web:68e8be478bbda1db601d08',
    messagingSenderId: '467627933593',
    projectId: 'spotifytr-19e9d',
    authDomain: 'spotifytr-19e9d.firebaseapp.com',
    storageBucket: 'spotifytr-19e9d.firebasestorage.app',
    measurementId: 'G-N76S8S1ND4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgEhg7ZuL6KMEoNWXjPa3AaAm6eGEJDS0',
    appId: '1:467627933593:android:2e6e5bfce3c44d91601d08',
    messagingSenderId: '467627933593',
    projectId: 'spotifytr-19e9d',
    storageBucket: 'spotifytr-19e9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNsMEqJqkd2P2Dp-6c4UR3nAv2eov7jxo',
    appId: '1:467627933593:ios:66b6d87610961ddb601d08',
    messagingSenderId: '467627933593',
    projectId: 'spotifytr-19e9d',
    storageBucket: 'spotifytr-19e9d.firebasestorage.app',
    iosBundleId: 'com.example.spotifyCloneTr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNsMEqJqkd2P2Dp-6c4UR3nAv2eov7jxo',
    appId: '1:467627933593:ios:66b6d87610961ddb601d08',
    messagingSenderId: '467627933593',
    projectId: 'spotifytr-19e9d',
    storageBucket: 'spotifytr-19e9d.firebasestorage.app',
    iosBundleId: 'com.example.spotifyCloneTr',
  );
}
